services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"

  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    ports:
      - "8081:8081"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8081


